### ISSUE TITLE
Question on getting metadata for generated asset

### ISSUE THREAD

**Issue by shark8me** [DEX-Company/starfish-py#100]
Before the question,here's the (oversimplified) scenario:

- A user(data scientist) purchases an asset (lets call it training_dataset)
- User purchases an invokable service (lets say its a model training service)
- The user invokes the service with the training_dataset argument. The service generates a new asset named 'trained_model'

Note that the 
- agent (running the service) doesn't allow the trained_model to be downloaded. 
- the data scientist makes the call to invoke the service remotely (the agent is in a different data center).

At this point, the Invoke service has to register the generated asset 'trained_model'. The invoke service needs some information about the new asset in order to register the dataset. 

My question is, what is the mininum information that needs to be provided by the agent (running the service) ?

- Since assets as immutable, is it limited to the hash of the dataset ?

**Comment by mikera** [comment]
I think there are two separate things the agent needs to do:
- Ensure the result asset metadata is registered *somewhere*. This could be either by putting it on another metadata agent, or by being itself a metadata agent and storing the metadata in its own local storage
- Return a DID that refers to the above to the caller (in the general case, I guess this needs to be async, e.g. the caller polls to see if the job is complete and gets the DID back when it is)

Returning a DID gives the flexibility for different agent implementations to decide where they put the result metadata - the caller can resolve this to get the asset metadata from whichever endpoint is appropriate.

Does that make sense?

**Comment by shark8me** [comment]
Agreed on this approach, hence marking resolved. Current implementations return DIDs or asset IDs, and the corresponding agent may allow download of the asset content.
