### ISSUE TITLE
What is the purpose of this repo?

### ISSUE THREAD

**Issue by kremalicious** [DEX-Company/starfish-py#154]
What functionality is intended to be added here which can't be done with squid-py? Is it solving a specific Dex use case only? Is it intended for Ocean Protocol community? Read me says "Currently only provide basic account balance information". Why not contribute new features to squid-py instead?

For all users coming to this repo from Google: use Ocean Protocol's official client to connect to one of the networks with Python: https://github.com/oceanprotocol/squid-py

**Comment by mikera** [comment]
Hi @kremalicious , good question!

Starfish is an open source developer toolkit, based on open standards and designed to enable developers to build applications and use cases making use of decentralised data supply lines. More information on the overall approach is available in DEP3 Architecture document here: https://github.com/DEX-Company/DEPs/tree/master/3

As such, it is not an either/or decision whether to use Squid or Starfish, they serve different purposes. Indeed, Starfish makes use of Squid as a dependency in situations where the user needs to make use of functionality on the Ocean Network.
