### ISSUE TITLE
Agent Storage class to provide reading writing of asset meta data with Surfer

### ISSUE THREAD

**Issue by mikera** [DEX-Company/starfish-py#32]
In the event that an Agent supports the Meta API (e.g. Surfer) the appropriate Agent subclass should implement registration and retreival of asset metadata from the remote agent.

Suggested pseudo-API for a round trip:
```
asset_id = agent.register_asset(meta)
asset = agent.get_asset(assetID)
meta =asset.metadata()
```

**Comment by billbsing** [comment]
This is now implemented
