### ISSUE TITLE
Asset classes - artifacts need better names

### ISSUE THREAD

**Issue by shark8me** [DEX-Company/starfish-py#84]
When I read the API for the Asset class, I feel that the Asset class represents several different "kinds of things".  (p.s. I'm also wearing the hat of a developer who has worked with other Dataset APIs (since we mostly equate an asset with a dataset). Example of dataset API [BigQuery](https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/com/google/cloud/bigquery/Dataset.html) and [Spark](https://spark.apache.org/docs/2.3.0/api/java/index.html?org/apache/spark/sql/Dataset.html) ). 

To a developer, an asset can refer to one of

- asset metadata
- raw bytes of the asset
- link or reference to an asset (e.g a remote asset on a cloud server)

An asset can also go through different temporal states

- pre-registered to registered
- pre-purchased to purchased
- reference to reified (e.g. something similar to `asset.getBytes().to_dataframe().filterrows( filter-fn)`

One possible solution is to have different names for these artifacts (just some suggestions here)

- AssetInfo /AssetRef (an object that represents information about the asset, such as DID, metadata, provenance). 
- PurchasedAsset (an object that has methods to perform actions on an asset, such as get bytes, verify checksums, invoke operations)
- LocalAsset/RemoteAsset (sub-types of purchased assets. Methods: `LocalAsset.getBytes(), RemoteAsset.invokeOperation()`

It would also enable platform specific-tools such as Spark or Pandas to use type specific functionality. Example: Spark would need a RemoteAsset whereas Pandas needs the bytes locally
```python
## import an Ocean-Spark bridge library
from ocean.spark import create_dataset,create_ocean_asset

## first purchase and get a RemoteAsset 
AssetInfo ai = ocn.get_asset(did)
PurchasedAsset pa= ai.purchase(account)
RemoteAsset ra = pa.getRemoteAsset()

## Spark code to transform the dataset (in a different server) and register the transformed dataset
AssetInfo nai=create_dataset(ra).map(..).filter(..).collect().create_ocean_asset()
ocn.registerAsset(nai)

## Examine provenance
nai.getProvenance()

```

Similarly, with pandas for assets that are downloadable
```python
from ocean.pandas import create_dataframe, create_ocean_asset

df=create_dataframe(pa) ## downloads the bytes and creates a data frame
## Select rows where year is 2002
newdf= df['year']==2002
AssetInfo ai=create_ocean_asset(newdf)
ocn.registerAsset(ai)

```
Thoughts?

**Comment by mikera** [comment]
Notes from conversation between @billbsing @mikera and @shark8me 

a) We need to separate "Listing" and "Asset" abstraction in the Starfish API where Listing is a mutable thing with price, service agreements etc. and Asset is a representation of the actual Dataset or Operation. This maps neatly to surfer, can probably also map to Brizo / Aquarius although they don't have a concrete representation of the actual asset value (the Aquarius DDO is basically a Listing)

b) When you purchase a Listing, you get back an Asset. This might be represented as a "PurchasedAsset" implementation class under the hood.

c) It would be potentially possible to have an Agent class that is local, e.g. representing a Spark cluster which you can access from the local machine. Then stuff like `sparkAgent.invoke(sparkOperation,param1,param2) can work in a local context.

b) Should also be possible to have a "LocalAsset" implementation that represents a file on disk or in memory. Should be useful for testing purposes etc.

**Comment by mikera** [comment]
ne possible solution is to have different names for these artifacts (just some suggestions here)
> 
> * AssetInfo /AssetRef (an object that represents information about the asset, such as DID, metadata, provenance).
> * PurchasedAsset (an object that has methods to perform actions on an asset, such as get bytes, verify checksums, invoke operations)
> * LocalAsset/RemoteAsset (sub-types of purchased assets. Methods: `LocalAsset.getBytes(), RemoteAsset.invokeOperation()`
> 

To me these are all potential implementations of the Asset abstraction. Though they probably shouldn't be separate classes - more likely differences in properties or method behaviour. I'm expecting assets to have functionality like:

```
asset.getBytes()
asset.getMetadata()
agent.invoke(asset,arg1,arg2)
asset.getProvenance()
```
etc. 

Subclasses can implement these as desired (throwing exceptions if a method is not supported e.g. getBytes() on a remote asset that cannot be downloaded.
